-- MySQL Script generated by MySQL Workbench
-- Fri Oct 24 16:38:52 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema autoreserve
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `autoreserve` ;

-- -----------------------------------------------------
-- Schema autoreserve
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `autoreserve` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ;
USE `autoreserve` ;

-- -----------------------------------------------------
-- Table `autoreserve`.`categoria`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `autoreserve`.`categoria` ;

CREATE TABLE IF NOT EXISTS `autoreserve`.`categoria` (
  `id_categoria` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NOT NULL,
  `descripcion` TEXT NULL DEFAULT NULL,
  `imagen` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id_categoria`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `autoreserve`.`sede`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `autoreserve`.`sede` ;

CREATE TABLE IF NOT EXISTS `autoreserve`.`sede` (
  `id_sede` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NOT NULL,
  `direccion` VARCHAR(255) NULL DEFAULT NULL,
  `ciudad` VARCHAR(100) NULL DEFAULT NULL,
  `telefono` VARCHAR(30) NULL DEFAULT NULL,
  PRIMARY KEY (`id_sede`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `autoreserve`.`auto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `autoreserve`.`auto` ;

CREATE TABLE IF NOT EXISTS `autoreserve`.`auto` (
  `id_auto` INT NOT NULL AUTO_INCREMENT,
  `marca` VARCHAR(100) NOT NULL,
  `modelo` VARCHAR(100) NOT NULL,
  `anio` YEAR NULL DEFAULT NULL,
  `placa` VARCHAR(20) NULL DEFAULT NULL,
  `precio_dia` DECIMAL(10,2) NOT NULL,
  `estado` ENUM('disponible', 'reservado', 'mantenimiento') NULL DEFAULT 'disponible',
  `id_categoria` INT NULL DEFAULT NULL,
  `id_sede` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id_auto`),
  UNIQUE INDEX `placa` (`placa` ASC) VISIBLE,
  INDEX `id_categoria` (`id_categoria` ASC) VISIBLE,
  INDEX `id_sede` (`id_sede` ASC) VISIBLE,
  CONSTRAINT `auto_ibfk_1`
    FOREIGN KEY (`id_categoria`)
    REFERENCES `autoreserve`.`categoria` (`id_categoria`),
  CONSTRAINT `auto_ibfk_2`
    FOREIGN KEY (`id_sede`)
    REFERENCES `autoreserve`.`sede` (`id_sede`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `autoreserve`.`rol`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `autoreserve`.`rol` ;

CREATE TABLE IF NOT EXISTS `autoreserve`.`rol` (
  `id_rol` INT NOT NULL AUTO_INCREMENT,
  `nombre_rol` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id_rol`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `autoreserve`.`usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `autoreserve`.`usuario` ;

CREATE TABLE IF NOT EXISTS `autoreserve`.`usuario` (
  `id_usuario` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NOT NULL,
  `apellido` VARCHAR(100) NULL DEFAULT NULL,
  `email` VARCHAR(150) NOT NULL,
  `password_hash` VARCHAR(255) NOT NULL,
  `telefono` VARCHAR(30) NULL DEFAULT NULL,
  `fecha_registro` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `id_rol` INT NOT NULL,
  PRIMARY KEY (`id_usuario`),
  UNIQUE INDEX `email` (`email` ASC) VISIBLE,
  INDEX `id_rol` (`id_rol` ASC) VISIBLE,
  CONSTRAINT `usuario_ibfk_1`
    FOREIGN KEY (`id_rol`)
    REFERENCES `autoreserve`.`rol` (`id_rol`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `autoreserve`.`reserva`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `autoreserve`.`reserva` ;

CREATE TABLE IF NOT EXISTS `autoreserve`.`reserva` (
  `id_reserva` INT NOT NULL AUTO_INCREMENT,
  `id_usuario` INT NOT NULL,
  `id_auto` INT NOT NULL,
  `fecha_inicio` DATE NOT NULL,
  `fecha_fin` DATE NOT NULL,
  `estado` ENUM('pendiente', 'confirmada', 'cancelada') NULL DEFAULT 'pendiente',
  `total` DECIMAL(10,2) NULL DEFAULT NULL,
  PRIMARY KEY (`id_reserva`),
  INDEX `id_usuario` (`id_usuario` ASC) VISIBLE,
  INDEX `id_auto` (`id_auto` ASC) VISIBLE,
  CONSTRAINT `reserva_ibfk_1`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `autoreserve`.`usuario` (`id_usuario`),
  CONSTRAINT `reserva_ibfk_2`
    FOREIGN KEY (`id_auto`)
    REFERENCES `autoreserve`.`auto` (`id_auto`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `autoreserve`.`pago`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `autoreserve`.`pago` ;

CREATE TABLE IF NOT EXISTS `autoreserve`.`pago` (
  `id_pago` INT NOT NULL AUTO_INCREMENT,
  `id_reserva` INT NULL DEFAULT NULL,
  `monto` DECIMAL(10,2) NOT NULL,
  `medio_pago` ENUM('tarjeta', 'transferencia', 'efectivo') NOT NULL,
  `fecha_pago` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `estado` ENUM('exitoso', 'fallido', 'pendiente') NULL DEFAULT 'pendiente',
  PRIMARY KEY (`id_pago`),
  UNIQUE INDEX `id_reserva` (`id_reserva` ASC) VISIBLE,
  CONSTRAINT `pago_ibfk_1`
    FOREIGN KEY (`id_reserva`)
    REFERENCES `autoreserve`.`reserva` (`id_reserva`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `autoreserve`.`factura`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `autoreserve`.`factura` ;

CREATE TABLE IF NOT EXISTS `autoreserve`.`factura` (
  `id_factura` INT NOT NULL AUTO_INCREMENT,
  `id_pago` INT NULL DEFAULT NULL,
  `numero_factura` VARCHAR(50) NOT NULL,
  `fecha_emision` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `monto_total` DECIMAL(10,2) NULL DEFAULT NULL,
  `detalles` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`id_factura`),
  UNIQUE INDEX `numero_factura` (`numero_factura` ASC) VISIBLE,
  UNIQUE INDEX `id_pago` (`id_pago` ASC) VISIBLE,
  CONSTRAINT `factura_ibfk_1`
    FOREIGN KEY (`id_pago`)
    REFERENCES `autoreserve`.`pago` (`id_pago`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `autoreserve`.`favorito`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `autoreserve`.`favorito` ;

CREATE TABLE IF NOT EXISTS `autoreserve`.`favorito` (
  `id_favorito` INT NOT NULL AUTO_INCREMENT,
  `id_usuario` INT NOT NULL,
  `id_auto` INT NOT NULL,
  `fecha_agregado` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id_favorito`),
  UNIQUE INDEX `id_usuario` (`id_usuario` ASC, `id_auto` ASC) VISIBLE,
  INDEX `id_auto` (`id_auto` ASC) VISIBLE,
  CONSTRAINT `favorito_ibfk_1`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `autoreserve`.`usuario` (`id_usuario`),
  CONSTRAINT `favorito_ibfk_2`
    FOREIGN KEY (`id_auto`)
    REFERENCES `autoreserve`.`auto` (`id_auto`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `autoreserve`.`notificacion`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `autoreserve`.`notificacion` ;

CREATE TABLE IF NOT EXISTS `autoreserve`.`notificacion` (
  `id_notificacion` INT NOT NULL AUTO_INCREMENT,
  `id_usuario` INT NOT NULL,
  `mensaje` TEXT NOT NULL,
  `tipo` ENUM('reserva', 'pago', 'alerta') NULL DEFAULT 'alerta',
  `fecha_envio` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `leida` TINYINT(1) NULL DEFAULT '0',
  PRIMARY KEY (`id_notificacion`),
  INDEX `id_usuario` (`id_usuario` ASC) VISIBLE,
  CONSTRAINT `notificacion_ibfk_1`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `autoreserve`.`usuario` (`id_usuario`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `autoreserve`.`perfil_usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `autoreserve`.`perfil_usuario` ;

CREATE TABLE IF NOT EXISTS `autoreserve`.`perfil_usuario` (
  `id_perfil` INT NOT NULL AUTO_INCREMENT,
  `id_usuario` INT NULL DEFAULT NULL,
  `direccion` VARCHAR(255) NULL DEFAULT NULL,
  `ciudad` VARCHAR(100) NULL DEFAULT NULL,
  `fecha_nacimiento` DATE NULL DEFAULT NULL,
  `licencia_conduccion` VARCHAR(100) NULL DEFAULT NULL,
  PRIMARY KEY (`id_perfil`),
  UNIQUE INDEX `id_usuario` (`id_usuario` ASC) VISIBLE,
  CONSTRAINT `perfil_usuario_ibfk_1`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `autoreserve`.`usuario` (`id_usuario`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `autoreserve`.`resena`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `autoreserve`.`resena` ;

CREATE TABLE IF NOT EXISTS `autoreserve`.`resena` (
  `id_resena` INT NOT NULL AUTO_INCREMENT,
  `id_usuario` INT NOT NULL,
  `id_auto` INT NOT NULL,
  `calificacion` TINYINT NULL DEFAULT NULL,
  `comentario` TEXT NULL DEFAULT NULL,
  `fecha` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id_resena`),
  INDEX `id_usuario` (`id_usuario` ASC) VISIBLE,
  INDEX `id_auto` (`id_auto` ASC) VISIBLE,
  CONSTRAINT `resena_ibfk_1`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `autoreserve`.`usuario` (`id_usuario`),
  CONSTRAINT `resena_ibfk_2`
    FOREIGN KEY (`id_auto`)
    REFERENCES `autoreserve`.`auto` (`id_auto`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
