-- MySQL Script generated by MySQL Workbench
-- Sat Aug 15 10:18:32 2026
-- Model: New Model    Version: 2.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema autoreserve_app_bd
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema autoreserve_app_bd
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `autoreserve_app_bd` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `autoreserve_app_bd` ;

-- -----------------------------------------------------
-- Table `autoreserve_app_bd`.`branch`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `autoreserve_app_bd`.`branch` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `address` VARCHAR(255) NULL DEFAULT NULL,
  `city` VARCHAR(100) NULL DEFAULT NULL,
  `image` VARCHAR(500) NULL DEFAULT NULL,
  `name` VARCHAR(100) NOT NULL,
  `phone` VARCHAR(30) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `autoreserve_app_bd`.`category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `autoreserve_app_bd`.`category` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `description` TEXT NULL DEFAULT NULL,
  `image` VARCHAR(255) NULL DEFAULT NULL,
  `name` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `autoreserve_app_bd`.`car_model`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `autoreserve_app_bd`.`car_model` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `brand` VARCHAR(100) NOT NULL,
  `description` VARCHAR(1000) NULL DEFAULT NULL,
  `image` VARCHAR(500) NULL DEFAULT NULL,
  `model` VARCHAR(100) NOT NULL,
  `price_per_day` DECIMAL(10,2) NOT NULL,
  `year` INT NULL DEFAULT NULL,
  `category_id` BIGINT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `FKefcq72dru98brmt7stk8h19jd` (`category_id` ASC) VISIBLE,
  CONSTRAINT `FKefcq72dru98brmt7stk8h19jd`
    FOREIGN KEY (`category_id`)
    REFERENCES `autoreserve_app_bd`.`category` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `autoreserve_app_bd`.`car`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `autoreserve_app_bd`.`car` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `color` VARCHAR(50) NULL DEFAULT NULL,
  `notes` VARCHAR(500) NULL DEFAULT NULL,
  `plate` VARCHAR(20) NULL DEFAULT NULL,
  `status` ENUM('AVAILABLE', 'MAINTENANCE', 'OUT_OF_SERVICE', 'PENDING_REGISTRATION', 'RENTED') NOT NULL,
  `branch_id` BIGINT NOT NULL,
  `car_model_id` BIGINT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `UKpvp69n7acjyr5racokd4pdr4t` (`plate` ASC) VISIBLE,
  INDEX `FK3lp0ybvpos5gv3hmn861hc5bj` (`branch_id` ASC) VISIBLE,
  INDEX `FKgfht1l5lcn8gbugha10mnt4bg` (`car_model_id` ASC) VISIBLE,
  CONSTRAINT `FK3lp0ybvpos5gv3hmn861hc5bj`
    FOREIGN KEY (`branch_id`)
    REFERENCES `autoreserve_app_bd`.`branch` (`id`),
  CONSTRAINT `FKgfht1l5lcn8gbugha10mnt4bg`
    FOREIGN KEY (`car_model_id`)
    REFERENCES `autoreserve_app_bd`.`car_model` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 9
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `autoreserve_app_bd`.`role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `autoreserve_app_bd`.`role` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `UK8sewwnpamngi6b1dwaa88askk` (`name` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `autoreserve_app_bd`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `autoreserve_app_bd`.`user` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `created_at` DATETIME(6) NOT NULL,
  `email` VARCHAR(150) NOT NULL,
  `first_name` VARCHAR(100) NOT NULL,
  `last_name` VARCHAR(100) NULL DEFAULT NULL,
  `password_hash` VARCHAR(255) NOT NULL,
  `phone` VARCHAR(30) NULL DEFAULT NULL,
  `status` ENUM('ACTIVE', 'INACTIVE', 'SUSPENDED') NULL DEFAULT NULL,
  `role_id` BIGINT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `UKhl4ga9r00rh51mdaf20hmnslt` (`email` ASC) VISIBLE,
  INDEX `FKdl9dqp078pc03g6kdnxmnlqpc` (`role_id` ASC) VISIBLE,
  CONSTRAINT `FKdl9dqp078pc03g6kdnxmnlqpc`
    FOREIGN KEY (`role_id`)
    REFERENCES `autoreserve_app_bd`.`role` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 12
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `autoreserve_app_bd`.`contact_message`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `autoreserve_app_bd`.`contact_message` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `created_at` DATETIME(6) NOT NULL,
  `sender_email` VARCHAR(200) NOT NULL,
  `sender_name` VARCHAR(100) NOT NULL,
  `status` ENUM('ANSWERED', 'CLOSED', 'IN_PROGRESS', 'OPEN') NOT NULL,
  `subject` VARCHAR(200) NOT NULL,
  `type` ENUM('FELICITACION', 'PREGUNTA', 'QUEJA', 'RECLAMO', 'SOLICITUD') NOT NULL,
  `updated_at` DATETIME(6) NULL DEFAULT NULL,
  `user_id` BIGINT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `FK5txug6yc9kmxtrworwtdk7q0` (`user_id` ASC) VISIBLE,
  CONSTRAINT `FK5txug6yc9kmxtrworwtdk7q0`
    FOREIGN KEY (`user_id`)
    REFERENCES `autoreserve_app_bd`.`user` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 7
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `autoreserve_app_bd`.`faq`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `autoreserve_app_bd`.`faq` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `answer` TEXT NOT NULL,
  `question` VARCHAR(300) NOT NULL,
  `sort_order` INT NOT NULL,
  `updated_at` DATETIME(6) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `autoreserve_app_bd`.`favorite`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `autoreserve_app_bd`.`favorite` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `created_at` DATETIME(6) NOT NULL,
  `car_model_id` BIGINT NOT NULL,
  `user_id` BIGINT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `UKambn45ye5xy57oub7tw574jrx` (`user_id` ASC, `car_model_id` ASC) VISIBLE,
  INDEX `FKbca8tjx3mf5o6mb0999dc370d` (`car_model_id` ASC) VISIBLE,
  CONSTRAINT `FKbca8tjx3mf5o6mb0999dc370d`
    FOREIGN KEY (`car_model_id`)
    REFERENCES `autoreserve_app_bd`.`car_model` (`id`),
  CONSTRAINT `FKsurf7pofpy2i6dix4yfvqbvik`
    FOREIGN KEY (`user_id`)
    REFERENCES `autoreserve_app_bd`.`user` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 9
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `autoreserve_app_bd`.`reservation`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `autoreserve_app_bd`.`reservation` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `created_at` DATETIME(6) NOT NULL,
  `end_date` DATE NOT NULL,
  `payment_status` ENUM('NO_PAYMENT', 'PAID', 'REFUNDED', 'REFUND_PENDING') NOT NULL,
  `price_per_day` DECIMAL(10,2) NULL DEFAULT NULL,
  `start_date` DATE NOT NULL,
  `status` ENUM('CANCELLED', 'COMPLETED', 'CONFIRMED', 'IN_PROGRESS', 'PENDING') NOT NULL,
  `total_amount` DECIMAL(10,2) NULL DEFAULT NULL,
  `total_days` INT NULL DEFAULT NULL,
  `car_id` BIGINT NULL DEFAULT NULL,
  `car_model_id` BIGINT NOT NULL,
  `dropoff_branch_id` BIGINT NULL DEFAULT NULL,
  `pickup_branch_id` BIGINT NULL DEFAULT NULL,
  `user_id` BIGINT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `FKgkmbspv7rljixxoxo1af80lpp` (`car_id` ASC) VISIBLE,
  INDEX `FK87269ugbm1h9escakwm8krhb6` (`car_model_id` ASC) VISIBLE,
  INDEX `FK2fmyrbylt3jps5x8ybnmqkl3n` (`dropoff_branch_id` ASC) VISIBLE,
  INDEX `FK5gjpg12pkc013i2ethdo2v5u1` (`pickup_branch_id` ASC) VISIBLE,
  INDEX `FKqr6cl4t61j8winj6g51rp83ei` (`user_id` ASC) VISIBLE,
  CONSTRAINT `FK2fmyrbylt3jps5x8ybnmqkl3n`
    FOREIGN KEY (`dropoff_branch_id`)
    REFERENCES `autoreserve_app_bd`.`branch` (`id`),
  CONSTRAINT `FK5gjpg12pkc013i2ethdo2v5u1`
    FOREIGN KEY (`pickup_branch_id`)
    REFERENCES `autoreserve_app_bd`.`branch` (`id`),
  CONSTRAINT `FK87269ugbm1h9escakwm8krhb6`
    FOREIGN KEY (`car_model_id`)
    REFERENCES `autoreserve_app_bd`.`car_model` (`id`),
  CONSTRAINT `FKgkmbspv7rljixxoxo1af80lpp`
    FOREIGN KEY (`car_id`)
    REFERENCES `autoreserve_app_bd`.`car` (`id`),
  CONSTRAINT `FKqr6cl4t61j8winj6g51rp83ei`
    FOREIGN KEY (`user_id`)
    REFERENCES `autoreserve_app_bd`.`user` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `autoreserve_app_bd`.`payment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `autoreserve_app_bd`.`payment` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `amount` DECIMAL(10,2) NOT NULL,
  `payment_date` DATETIME(6) NULL DEFAULT NULL,
  `payment_method` ENUM('CARD', 'CASH', 'TRANSFER') NOT NULL,
  `status` ENUM('NO_PAYMENT', 'PAID', 'REFUNDED', 'REFUND_PENDING') NOT NULL,
  `reservation_id` BIGINT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `UK3llq7oxcs9j7vlujfdf16jmu` (`reservation_id` ASC) VISIBLE,
  CONSTRAINT `FKrewpj5f9v9xehy4ga8g221nw1`
    FOREIGN KEY (`reservation_id`)
    REFERENCES `autoreserve_app_bd`.`reservation` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `autoreserve_app_bd`.`invoice`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `autoreserve_app_bd`.`invoice` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `details` TEXT NULL DEFAULT NULL,
  `invoice_number` VARCHAR(50) NOT NULL,
  `issue_date` DATETIME(6) NULL DEFAULT NULL,
  `total_amount` DECIMAL(10,2) NULL DEFAULT NULL,
  `payment_id` BIGINT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `UKt6xkdjx1qtd5whp2iljdfn2yj` (`invoice_number` ASC) VISIBLE,
  UNIQUE INDEX `UK5vvlr4mmb6jbwiu4dyqwevd0d` (`payment_id` ASC) VISIBLE,
  CONSTRAINT `FKbaxa82hce5x7dqj0sotnc1cxf`
    FOREIGN KEY (`payment_id`)
    REFERENCES `autoreserve_app_bd`.`payment` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `autoreserve_app_bd`.`message_reply`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `autoreserve_app_bd`.`message_reply` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `author_name` VARCHAR(100) NOT NULL,
  `content` TEXT NOT NULL,
  `created_at` DATETIME(6) NOT NULL,
  `sent_by` ENUM('ADMIN', 'CLIENT') NOT NULL,
  `contact_message_id` BIGINT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `FKdmbotl2yecuxryvgoglp5ww5r` (`contact_message_id` ASC) VISIBLE,
  CONSTRAINT `FKdmbotl2yecuxryvgoglp5ww5r`
    FOREIGN KEY (`contact_message_id`)
    REFERENCES `autoreserve_app_bd`.`contact_message` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 11
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `autoreserve_app_bd`.`notification`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `autoreserve_app_bd`.`notification` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `message` TEXT NOT NULL,
  `read_flag` BIT(1) NOT NULL,
  `sent_at` DATETIME(6) NULL DEFAULT NULL,
  `type` ENUM('ALERT', 'PAYMENT', 'RESERVATION') NOT NULL,
  `user_id` BIGINT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `FKspjuqpmul833046oftkpgmr8a` (`user_id` ASC) VISIBLE,
  CONSTRAINT `FKspjuqpmul833046oftkpgmr8a`
    FOREIGN KEY (`user_id`)
    REFERENCES `autoreserve_app_bd`.`user` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `autoreserve_app_bd`.`policy`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `autoreserve_app_bd`.`policy` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `content` TEXT NOT NULL,
  `slug` VARCHAR(50) NOT NULL,
  `sort_order` INT NOT NULL,
  `title` VARCHAR(200) NOT NULL,
  `updated_at` DATETIME(6) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `autoreserve_app_bd`.`review`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `autoreserve_app_bd`.`review` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `comment` TEXT NULL DEFAULT NULL,
  `created_at` DATETIME(6) NOT NULL,
  `rating` INT NOT NULL,
  `car_id` BIGINT NOT NULL,
  `user_id` BIGINT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `FKoie88l9xdqjv41ym8c1s7valq` (`car_id` ASC) VISIBLE,
  INDEX `FKj8m0asijw8lfl4jxhcps8tf4y` (`user_id` ASC) VISIBLE,
  CONSTRAINT `FKj8m0asijw8lfl4jxhcps8tf4y`
    FOREIGN KEY (`user_id`)
    REFERENCES `autoreserve_app_bd`.`user` (`id`),
  CONSTRAINT `FKoie88l9xdqjv41ym8c1s7valq`
    FOREIGN KEY (`car_id`)
    REFERENCES `autoreserve_app_bd`.`car` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `autoreserve_app_bd`.`user_profile`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `autoreserve_app_bd`.`user_profile` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `address` VARCHAR(255) NULL DEFAULT NULL,
  `birth_date` DATE NULL DEFAULT NULL,
  `city` VARCHAR(100) NULL DEFAULT NULL,
  `driving_license` VARCHAR(100) NULL DEFAULT NULL,
  `user_id` BIGINT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `UKebc21hy5j7scdvcjt0jy6xxrv` (`user_id` ASC) VISIBLE,
  CONSTRAINT `FKqcd5nmg7d7ement27tt9sf3bi`
    FOREIGN KEY (`user_id`)
    REFERENCES `autoreserve_app_bd`.`user` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
